proxy:
  hide-navbar: true
  landing-page: /
  ## this keeps the app controls working for 24 hours
  container-wait-time: 86400000
  ## this stops app "gray-out" if e.g. switch tabs on mobile
  heartbeat-timeout: 86400000
  port: 8080
  template-path: ./
  authentication: none
  ## for cognito authentication: uncomment, replace {} below and set authentication to openid
  # openid:
  #   roles-claim: cognito:groups
  #   auth-url: https://{cognito_domain_prefix}.auth.{region}.amazoncognito.com/oauth2/authorize
  #   token-url: https://{cognito_domain_prefix}.auth.{region}.amazoncognito.com/oauth2/token
  #   jwks-url: https://cognito-idp.{region}.amazonaws.com/{userPoolId}/.well-known/jwks.json
  #   logout-url: https://{cognito_domain_prefix}.auth.{region}.amazoncognito.com/logout?client_id={client_id}&logout_uri={your_host_url}
  #   client-id:
  #   client-secret:
  ## Docker configuration
  docker:
    internal-networking: true
  specs:
  - id: example
    display-name: drugseqr
    description: Example of drugseqr application
    container-image: alexvpickering/drugseqr
    container-cmd: ["R", "-e", "drugseqr::run_drugseqr('example')"]
    container-volumes: ["/srv/drugseqr:/srv/drugseqr"]
    container-network: sp-example-net
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
logging:
  file:
    shinyproxy.log
server:
    servlet.session.timeout: 0
