proxy:
  hide-navbar: true
  landing-page: /
  heartbeat-timeout: 6000000
  port: 8080
  template-path: ./
  authentication: none
  # Docker configuration
  docker:
    internal-networking: true
  specs:
  - id: example
    display-name: drugseqr
    description: Example of drugseqr application
    container-image: drugseqr
    container-cmd: ["R", "-e", "drugseqr::run_drugseqr('example')"]
    container-volumes: ["/srv/drugseqr:/srv/drugseqr"]
    container-network: sp-example-net
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
    
logging:
  file:
    shinyproxy.log
