proxy:
  hide-navbar: true
  landing-page: /
  # this keeps the app controls working for 24 hours
  container-wait-time: 86400000
  # this stops app "gray-out" if e.g. switch tabs on mobile
  heartbeat-timeout: 86400000
  port: 8080
  template-path: ./
  # for cognito authentication: replace {} below and set authentication to openid
  authentication: none
  openid:
    roles-claim: cognito:groups
    auth-url: https://{auth_domain}/oauth2/authorize
    token-url: https://{auth_domain}/oauth2/token
    jwks-url: https://cognito-idp.{region}.amazonaws.com/{user_pool_id}/.well-known/jwks.json
    logout-url: https://{auth_domain}/logout?response_type=code&client_id={client_id}&redirect_uri=https://{host_url}/login/oauth2/code/shinyproxy
    client-id:
    client-secret:
  # Docker configuration
  docker:
    internal-networking: true
  specs:
  - id: private
    display-name: dseqr
    description: your private dseqr workspace
    container-image: alexvpickering/drugseqr
    container-cmd: ["R", "-e", "drugseqr::run_drugseqr(Sys.getenv('SHINYPROXY_USERNAME'), logout_url='https://{host_url}/logout')"]
    container-volumes: ["/srv/drugseqr:/srv/drugseqr"]
    container-network: sp-example-net
    logo-url: https://raw.githubusercontent.com/hms-dbmi/drugseqr.sp/master/ninja.png
  - id: admins
    display-name: dseqr admins
    description: dseqr application visible to admins
    container-image: alexvpickering/drugseqr
    container-cmd: ["R", "-e", "drugseqr::run_drugseqr('example', logout_url='https://{host_url}/logout')"]
    container-volumes: ["/srv/drugseqr:/srv/drugseqr"]
    container-network: sp-example-net
    logo-url: https://raw.githubusercontent.com/hms-dbmi/drugseqr.sp/master/ninja.svg
    access-groups: admins
  - id: demo
    display-name: dseqr demo
    description: dseqr application with demo data
    container-image: alexvpickering/drugseqr
    container-cmd: ["R", "-e", "drugseqr::run_drugseqr('example', logout_url='https://{host_url}/logout')"]
    container-volumes: ["/srv/drugseqr:/srv/drugseqr"]
    container-network: sp-example-net
    logo-url: https://raw.githubusercontent.com/hms-dbmi/drugseqr.sp/master/favicon.png
  - id: hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    container-network: sp-example-net
    logo-url: https://raw.githubusercontent.com/rstudio/shiny/master/man/figures/logo.png
logging:
  file:
    shinyproxy.log
server:
    useForwardHeaders: true # won't redirect to http (need for cognito)
    servlet.session.timeout: 0
